const apelidos = [
    "Abelho",
    "Aeromoço",
    "Alfaço",
    "Amoxilino",
    "Anito",
    "Arábio Saudito",
    "Araraquaro",
    "Bisteco",
    "Borboleto",
    "Braganço Paulisto",
    "Cadelo",
    "Calabreso",
    "Caldo de Cano",
    "Calopsito",
    "Camisinho",
    "Capivaro",
    "Caraguatatubo",
    "Carambolo",
    "Carniço",
    "Casos Bahio",
    "Cenouro",
    "Cerejo",
    "Cervejo",
    "Chavasco",
    "Chupeto",
    "Cibaleno",
    "Cláudia Raio",
    "Corvino",
    "Cracolândio",
    "Delício",
    "Dipirono",
    "Donzelo",
    "Fanto Laranjo",
    "Frigideiro",
    "Gasolino",
    "Geladeiro",
    "Hemorróido",
    "Inseticido",
    "Iphono",
    "Iveto Sangalo",
    "Jiboio",
    "Lacraio",
    "Lagartixo",
    "Lantejolo",
    "Lapiseiro",
    "Lasanho",
    "Lesmo",
    "Lombrigo",
    "Ludmilo",
    "Macaxero",
    "Madonno",
    "Magazino Luizo",
    "Mamadeiro",
    "Margarido",
    "Mato Atlântico",
    "Menopauso",
    "Menstruado",
    "Monaliso",
    "Mortadelo",
    "Mussarelo",
    "Panqueco",
    "Pastilho",
    "Patricio Poeto",
    "Perébo",
    "Perereco",
    "Pitango",
    "Prechéco",
    "Princeso",
    "Rito Cadillaco",
    "Saboneto",
    "Salado de Fruto",
    "Salsicho",
    "Samsungo",
    "Sandálio",
    "Sapopembo",
    "Seborréio",
    "Shakiro",
    "Silos Malafaio",
    "Sonho de Valso",
    "Tadalafilo",
    "Testosterono",
    "Tilápio",
    "Toscano",
    "Tubaíno",
    "Tutti-fruto",
    "Ubatubo",
    "Valesco Popozudo",
    "Virílio",
    "Xilocaíno",
    "Zebro"
];